cuda_visible_devices: 0

data_path: data/zvuk.csv # path to csv with structure as in after get_movielens_data(include_time=True)
splitting: 'temporal'

dataloader:
  batch_size: 64
  n_neg_samples: 0

model: 'SASRec' # not used
model_params:
  fwd_type: 'sce' # DO NOT CHANGE
  sampling: 'no_sampling' # DO NOT USE FOR CE AND RCE
  
  maxlen: 100
  hidden_units: 312
  num_blocks: 2
  num_heads: 2
  dropout_rate: 0.15
  
  n_buckets: 410
  bucket_size_x: 410
  bucket_size_y: 128
  mix_x: True # mix states embs with random matrix

trainer_params:
  num_epochs: 10
  patience: 10    # nmb of epoches to wait for improvement in validation metrics
  skip_epochs: 1  # how often to check if validation metrics are improved
  learning_rate: 0.001
  seed: 37
