#! /bin/bash

DOCKER_NAME="sce_container" # username in container
CONTAINER_NAME=$USER"-sce_rs" # name of container
SRC="fastrecsys/Scalable-SASRec" # source directory (supposedly, this repo's path is /home/${USER}/${SRC})

# to get these values type "id" in shell termilal
DOCKER_USER_ID=$(id -u) 
DOCKER_GROUP_ID=$(id -g)